
package redneuronal;

import javax.swing.ImageIcon;

/**
 *
 * @author abner
 */
public class Interfaz2 extends javax.swing.JFrame {
    //Creacion de las neuronas globales para poder usarlos en los demas metodos
    Neurona n1 = new Neurona(1, 1, 1, 1, 1, 1);
    Neurona n2 = new Neurona(1, 1, 1, 1, 1, 1);
    Neurona n3 = new Neurona(1, 1, 1, 1, 1, 1);
    Neurona n4 = new Neurona(1, 1, 1, 1, 1, 1);
    Neurona n5 = new Neurona(1, 1, 1, 1, 1, 1);
    Neurona n6 = new Neurona(1, 1, 1, 1, 1, 1);
    Neurona n7 = new Neurona(1, 1, 1, 1, 1, 1);     //PESOS EN 1 PARA QUE SOLO VAYAN VARIANDO DEPENDIENDO DE SUS ENTRADAS
    
    public Interfaz2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass ().getResource("/imagenes/Logo.png")).getImage());
        
        int iteraciones=100;//SI EXCEDEN LAS ITERACIONES NECESARIAS PUEDE QUE NO FUNCIONE OPTIMAMENTE
        for(int i=0; i<iteraciones; i++){ //CICLO DE ENTRENAMIENTO PARA NARANJAS
            
            int out1 = n1.fEntrenamiento_supervisado(1, 1, 1, 1, 1, 1, 1); //Condiciones ideales para que sea una naranja
            int out2 = n2.fEntrenamiento_supervisado(1, 2, 1, 3, 2, 1, 1); //El último parametro es el resultado deseado porque está en modo de entrenamiento
            int out3 = n3.fEntrenamiento_supervisado(1, 1, 2, 3, 2, 1, 1);
            int out4 = n4.fEntrenamiento_supervisado(1, 2, 3, 1, 2, 1, 1);
            int out5 = n4.fEntrenamiento_supervisado(3, 3, 3, 1, 1, 1, 1);
            int out6 = n4.fEntrenamiento_supervisado(3, 3, 3, 1, 1, 1, 1);
            int outf = n7.fEntrenamiento_supervisado(out1, out2, out3, out4, out5, out6, 1);//El último parametro es 1 representando a una Naranja y 0 Manzana
            
        }
        //OPCIONAL AGREGAR OTRO CICLO DE ENTRENAMIENTO CON DIFERENTES PARAMETROS
       /* for(int i=0; i<iteraciones; i++){ //CICLO DE ENTRENAMIENTO PARA MANZANAS
            
            int out1 = n1.fEntrenamiento_supervisado(4, 4, 4, 4, 3, 2, 0); //Condiciones ideales para que sea una naranja
            int out2 = n2.fEntrenamiento_supervisado(3, 3, 4, 5, 5, 2, 0); //El último parametro es el resultado deseado porque está en modo de entrenamiento
            int out3 = n3.fEntrenamiento_supervisado(5, 3, 5, 5, 4, 2, 0);
            int out4 = n4.fEntrenamiento_supervisado(4, 4, 3, 5, 6, 2, 0);
            int out5 = n4.fEntrenamiento_supervisado(6, 5, 5, 5, 3, 2, 0);
            int out6 = n4.fEntrenamiento_supervisado(3, 3, 3, 1, 1, 2, 0);
            int outf = n7.fEntrenamiento_supervisado(out1, out2, out3, out4, out5, out6, 0);//El último parametro es 1 representando a una Naranja y 0 Manzana
            
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color = new javax.swing.JComboBox<>();
        Textura = new javax.swing.JComboBox<>();
        Forma = new javax.swing.JComboBox<>();
        Sabor = new javax.swing.JComboBox<>();
        Olor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Interior = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Color.setBackground(new java.awt.Color(255, 255, 255));
        Color.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        Color.setForeground(new java.awt.Color(0, 0, 0));
        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color:", "Naranja-Rojizo", "Naranja", "Amarillo", "Verde", "Rojo" }));
        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });
        getContentPane().add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 150, -1));

        Textura.setBackground(new java.awt.Color(255, 255, 255));
        Textura.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        Textura.setForeground(new java.awt.Color(0, 0, 0));
        Textura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Textura", "Porosa", "Raspoza", "Rugoza", "Lisa", "Firme", "Sueve" }));
        getContentPane().add(Textura, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 150, -1));

        Forma.setBackground(new java.awt.Color(255, 255, 255));
        Forma.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        Forma.setForeground(new java.awt.Color(0, 0, 0));
        Forma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Forma", "Circular", "Ovalar", "Redonda", "Corazón", "Aplanada" }));
        getContentPane().add(Forma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 150, -1));

        Sabor.setBackground(new java.awt.Color(255, 255, 255));
        Sabor.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        Sabor.setForeground(new java.awt.Color(0, 0, 0));
        Sabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sabor", "Ácido", "Agridulce", "Amargo", "Dulce", "Seco" }));
        getContentPane().add(Sabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 150, -1));

        Olor.setBackground(new java.awt.Color(255, 255, 255));
        Olor.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        Olor.setForeground(new java.awt.Color(0, 0, 0));
        Olor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Olor", "Ácido", "Dulce", "Fresco", "Sutil", "Sin Olor" }));
        getContentPane().add(Olor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Deducir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        Interior.setBackground(new java.awt.Color(255, 255, 255));
        Interior.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        Interior.setForeground(new java.awt.Color(0, 0, 0));
        Interior.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interior", "Gajos", "Pulpa blanca" }));
        getContentPane().add(Interior, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 150, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 190, 130));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InterfazManual.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 698, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed

    }//GEN-LAST:event_ColorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            System.out.println(""+Color.getSelectedIndex());
            System.out.println(""+Textura.getSelectedIndex());
            System.out.println(""+Forma.getSelectedIndex());
            System.out.println(""+Sabor.getSelectedIndex());
            System.out.println(""+Olor.getSelectedIndex());
            System.out.println(""+Interior.getSelectedIndex());
            
            //RED DE IMPLEMENTACIÓN
            
            int out1 = n1.fSalida(Color.getSelectedIndex(), Textura.getSelectedIndex(), Forma.getSelectedIndex(), Sabor.getSelectedIndex(), Olor.getSelectedIndex(), Interior.getSelectedIndex());
            int out2 = n2.fSalida(Interior.getSelectedIndex(), Color.getSelectedIndex(), Textura.getSelectedIndex(), Forma.getSelectedIndex(), Sabor.getSelectedIndex(),Olor.getSelectedIndex());
            int out3 = n3.fSalida(Olor.getSelectedIndex(), Interior.getSelectedIndex(), Color.getSelectedIndex(), Textura.getSelectedIndex(), Forma.getSelectedIndex(), Sabor.getSelectedIndex());
            int out4 = n1.fSalida(Sabor.getSelectedIndex(), Olor.getSelectedIndex(), Interior.getSelectedIndex(), Color.getSelectedIndex(), Textura.getSelectedIndex(), Forma.getSelectedIndex());
            int out5 = n2.fSalida(Forma.getSelectedIndex(), Sabor.getSelectedIndex(), Olor.getSelectedIndex(), Interior.getSelectedIndex(), Color.getSelectedIndex(), Textura.getSelectedIndex());
            int out6 = n3.fSalida(Textura.getSelectedIndex(), Forma.getSelectedIndex(), Sabor.getSelectedIndex(), Olor.getSelectedIndex(), Interior.getSelectedIndex(), Color.getSelectedIndex());
            int outf = n7.fSalida(out1, out2, out3, out4, out5, out6);
            
            if(outf==1){
                jLabel2.setText("Naranja");
            }else{
                jLabel2.setText("Manzana");
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JComboBox<String> Forma;
    private javax.swing.JComboBox<String> Interior;
    private javax.swing.JComboBox<String> Olor;
    private javax.swing.JComboBox<String> Sabor;
    private javax.swing.JComboBox<String> Textura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
